/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/test.check" instead.
 */

#include <check.h>

#line 1 "test/test.check"
#include "../src/string21.h"
#include "test_string21.h"
#include <string.h>

START_TEST(test_strncmp21)
{
#line 6
  char str[N][MAX_LEN];
  get_strs(str);  
  int n[N];
  get_nums(n);

  for (int i = 0; i < N; ++i) {
    for (int j = 0; j < N; ++j) {
      for (int k = 0; k < N; ++k) {
        ck_assert_int_eq(strncmp21(str[i], str[j], n[k]),
                         strncmp(str[i], str[j], n[k]));
      }
    }
  }

}
END_TEST

START_TEST(test_memset21)
{
#line 21
  char str[N][MAX_LEN];
  get_strs(str);
  char c[N];
  get_chrs(c);
  int n[N];
  get_nums(n);

  for (int i = 0; i < N; ++i) {
    for (int j = 0; j < N; ++j) {
      for (int k = 0; k < N; ++k) {
        ck_assert_ptr_eq(memset21(str[i], c[j], (size_t) n[k]),
                         memset(str[i], c[j], (size_t) n[k]));
      }
    }
  }

}
END_TEST

START_TEST(test_strtok21)
{
#line 38
  char str[N][MAX_LEN];
  get_strs(str);
  char str21[N][MAX_LEN];
  get_strs(str21);
  char delim[N][MAX_LEN];
  get_delims(delim);

  for (int i = 0; i < N; ++i) {
    char *token = strtok(str[i], delim[i]);
    char *token21 = strtok21(str21[i], delim[i]);

    while (token != NULL && token21 != NULL) {
      ck_assert_str_eq(token, token21);
      token = strtok(NULL, delim[i]);
      token21 = strtok21(NULL, delim[i]);
    }
  }
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_strncmp21);
    tcase_add_test(tc1_1, test_memset21);
    tcase_add_test(tc1_1, test_strtok21);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
